Lesson 13: Api
popeskul/go-core pull request #12
Opened 2022-06-07 09:01 UTC by popeskul

Added swagger, logger middleware, tests

2022-06-09 08:18 UTC, DmitriyVTitov requested changes
Мьютекс используется неверно. Это важно.

2022-06-09 16:35 UTC, popeskul commented on hw13/pkg/api/api.go
> +}
@DmitriyVTitov перенёс `mux sync.Mutex` в пакет storage

2022-06-12 09:11 UTC, DmitriyVTitov requested changes
Структура программы не понятна. Предлагаю пересмотреть модель данных.
Модель данных, как правило, даже важнее чем код, который с ней работает.

2022-06-12 09:11 UTC, DmitriyVTitov commented on hw13/pkg/storage/memstore/memstore.go
> +}
мьютекс обычно объявляется перед защищаемым полем

2022-06-12 09:11 UTC, DmitriyVTitov commented on hw13/pkg/api/api.go
> +}
Что-то странное: почему тут есть массив документов И хранилище тоже с массивом документов? При этом далее в методах используется и этот встроенный массив и массив из пакета `storage`, к тому же `api.Docs` используется без всякой сериализации доступа при помощи мьютекса.
Это как есть передать в API копию БД. Зачем? Как они будут синхронизироваться?
И самое главное: объект API не должен хранить данные, это не его задача.

2022-06-15 21:33 UTC, DmitriyVTitov requested changes
Пока не могу принять. С инициализацией БД что-то явно не то.

2022-06-15 21:33 UTC, DmitriyVTitov commented on hw13/pkg/api/api.go
> +}
Опять нелогично. Почему конструктор API принимает какие-то документы и создаёт хранилище? Это не его задача.
Почему он не принимает `storage.Interface` также как и маршрутизатор?
Зависимости лучше создавать уровнем выше и передавать в конструктор. Что если БД нужна ещё где-то кроме API? Как её прокидывать?

2022-06-15 21:33 UTC, DmitriyVTitov commented on hw13/cmd/main.go
> +	app.storage.Add(docs)
Документы добавляются в БД здесь + в конструкторе API. Это нелогично. БД должна быть одна на всё приложение, инициализироваться в исполняемом пакете и далее передаваться в дочерние объекты как зависимость.

2022-06-23 17:08 UTC, DmitriyVTitov requested changes
Опять мьютекс используется неверно.
Описал подробно, с примером. Если идея всё равно не понятна - надо найти и почитать статьи на эту тему. Это очень важно!

2022-06-23 17:08 UTC, DmitriyVTitov commented on hw13/pkg/api/docs.go
> +	}
not found - страница не найдена, а не объект в БД
если объекта с таким id нет, то нужно выдать пустой ответ

2022-06-23 17:08 UTC, DmitriyVTitov commented on hw13/pkg/storage/memstore/memstore.go
> +}
Опять неверно.
Мьютекс - просто булева переменная. Сам он ничего не умеет, мы его создаём для себя же, мы (программисты) используем его в коде.
Здесь каждый запрос к API будет обрабатываться в отдельном потоке и в каждом потоке будет вызваться своя копия этой функции. В итоге в каждом потоке будет свой флажок (мьютекс).
А массив - один на все потоки, объявленный в объекте DB. Поэтому и мьютекс также должен быть общим для всех потоков, чтобы все потоки работали именно с одним и тем же мьютексов.
Т.е.:
```
type Storage struct {
  sync.Mutex
  docs []Document
  ...
}

func (db *DB) addDoc(d Document) {
  db.Lock()
  db.docs = append(db.docs, doc)
  db.Unlock()
}
```

2022-06-27 08:26 UTC, DmitriyVTitov approved these changes
ОК

2022-06-27 08:26 UTC, DmitriyVTitov commented on hw13/cmd/main.go
> +// @BasePath  /api/v1
Вот это всё только мешает, лучше не надо.

2022-06-27 08:26 UTC, DmitriyVTitov commented on hw13/pkg/api/docs.go
> +// @Failure 400 {object} string "Bad request"
жуть

2022-06-27 08:26 UTC, DmitriyVTitov commented on hw13/pkg/webapp/webapp_test.go
> +}
Не понятно. Тестов же нет.

2022-06-27 08:26 UTC, DmitriyVTitov commented on hw13/pkg/webapp/webapp.go
> +}
Для чего вообще этот пакет? Что он привносит в приложение?
Если вместо него использовать непосредственно пакет api, то что изменится?

2022-06-27 08:26 UTC, DmitriyVTitov commented on hw13/pkg/api/middleware.go
> +		ctx := context.WithValue(r.Context(), "request_id", rand.Intn(1_000_000))
обычно используют UUID

2022-06-27 20:01 UTC, popeskul commented on hw13/cmd/main.go
> +// @BasePath  /api/v1
В следующем задании уберу.

2022-06-27 20:17 UTC, popeskul commented on hw13/pkg/webapp/webapp.go
> +}
Перенёс в пакет api

2022-06-27 20:28 UTC, merged