HW4: io
popeskul/go-core pull request #4
Opened 2022-04-29 14:44 UTC by popeskul

2022-05-01 09:10 UTC, DmitriyVTitov requested changes
Ошибки не обрабатываются. Это критично.

2022-05-01 09:10 UTC, DmitriyVTitov commented on hw4/go.mod
> +module go-search
модуль должен быть один для всего курса
т.е. можно и так, но в этом нет особенного смысла

2022-05-01 09:10 UTC, DmitriyVTitov commented on hw4/cmd/go-search.go
> +func init() {
функцию `init()` не рекомендуется использовать из-за её неявного выполнения

2022-05-01 09:10 UTC, DmitriyVTitov commented on hw4/cmd/go-search.go
> +		defer f.Close()
действием на ошибку не может быть только текст на экране
при ошибка `f` будет `nil` и `f.Close()` вызовет панику

2022-05-01 09:10 UTC, DmitriyVTitov commented on hw4/cmd/go-search.go
> +func (s *searcher) run() {
run - плохое имя
да и функция, которая ничего не принимает и ничего не возвращает выглядит странно

`s.run()` - и всё, о чём говорит такой вызов? ни о чём :)

2022-05-04 17:48 UTC, DmitriyVTitov approved these changes
ОК

2022-05-04 17:48 UTC, DmitriyVTitov commented on hw4/cmd/go-search.go
> +	// scanning
желательно, чтобы комментарий отвечал на вопрос "зачем?", а не "что?"

2022-05-04 17:48 UTC, DmitriyVTitov commented on hw4/cmd/go-search.go
> +		}
опять ошибка не обработана
если я правильно понимаю, то здесь не удалось решить, что же с ней делать
если так, то я тоже не знаю

2022-05-04 17:48 UTC, DmitriyVTitov commented on hw4/cmd/go-search.go
> +}
я бы, скорее всего, попытался бы прочитать данные из файла и раскодировать в массив
если в итоговом массиве ничего нет - то просканировать сайты

текущий алгоритм выглядит запутанным, много условий

2022-05-05 12:57 UTC, popeskul commented on hw4/cmd/go-search.go
> +}
да, убрал

2022-05-05 13:02 UTC, merged